### PR TITLE
Update all telegram chats with notification

### PR DESCRIPTION
**Pull request by marmitesandwich**
Updated telegram notifier to handle multiple chats

### CODE REVIEW

**Comment by andytson** [comment]
updates only last 24 hours before Telegram removes them from the get updates call, so this will only send notifications if a message is posted to a channel within each day

**Comment by andytson** [comment]
I was playing about with Telegraf bot last night to see if I could get a way of hooking up chat ids from using bot commands, though would need quite a bit more time to flesh that out

**Comment by andytson** [comment]
I'll merge this for now though, as it makes it easier this change to start from just direct-messages (channel_post was only for channels)

**Comment by marmitesandwich** [comment]
public channels could be an answer or configuring the user id.
http://www.bernaerts-nicolas.fr/linux/75-debian/351-debian-send-telegram-notification

**Pull request merged**
