### PR TITLE
Collection slots

### PR DESCRIPTION
**Pull request by philharle**
Add additional check for click and collect slots

### CODE REVIEW

**Comment by andytson** [comment]
running `yarn lint:fix` and committing the changes should resolve all of the errors github is showing

**Comment by philharle** [comment]
> running `yarn lint:fix` and committing the changes should resolve all of the errors github is showing

Thank you. Looking better now :-)

**Comment by andytson** [comment]
I'd suggest we make delivery/collection a config.ini opt in option (with only delivery turned on in the example config, and assumed on by default if not declared in the configuration for backwards compatibility)

Not everyone will want collection, and this will help to reduce traffic on Tescos website when its not wanted.

**Comment by philharle** [comment]
Good call. I've added click and collect as an optional check now, with the default set to false.

**Comment by esticle** [comment]
Very nice, next step I suspect is to actually book a slot for you :)

**Comment by paulmaunders** [comment]
@andytson you are a far superior coder than me, so would you mind testing and merging this if you're happy with it? :)

**Comment by andytson** [comment]
@philharle I've re-implemented this in #24 with a lot of refactoring to reduce duplication (and as a start to support other supermarkets)

**Pull request closed without merging**
