### PR TITLE
Add a cookie store to bypass login for internal cron mode

### PR DESCRIPTION
**Pull request by andytson**
While it's possible to add file storage of this for external cron mode, features are going to get more verbose over time in state, so I'd personally prefer the internal cron mode to be the main way forward.

### CODE REVIEW

**Comment by andytson** [comment]
Might even be able to get away with checking every minute with this :)

**Comment by andytson** [comment]
Going to hold this open for a day, just to see it find slots before merge. Others are welcome to try it though by switching to the branch

**Comment by paulmaunders** [comment]
I was using the external cron because I'm running it on a server, but I guess I could just use the internal cron and run it on a 'screen'. Perhaps we could update our instructions to recommend that instead?

**Comment by SonnyJackson** [comment]
> I was using the external cron because I'm running it on a server, but I guess I could just use the internal cron and run it on a 'screen'. Perhaps we could update our instructions to recommend that instead?

Currently I'm running the bot on a free amazon aws server lol 
Did a test ping and it works so hopefully I can just keep it running 24/7 for free and I'll get a ping on my phone when a slot is out (:

**Comment by paulmaunders** [comment]
@JamesJackson123 If the test ping works, the script is returning 'no slots available', and you are using either the internal or external cron then you should be good to go.

@andytson I've switched my server to use the internal cron now, and it seems to be working fine preserving the login so far. I will keep an eye overnight too and we can merge tomorrow 👍

**Comment by andytson** [comment]
well that was interesting, I got alerted to the login page, and my account got locked

**Comment by andytson** [comment]
The lockout wasn't to do with this PR it appears (another account I stopped using the bot on also got locked out)

**Pull request merged**
